# Generated by Django 5.2.6 on 2025-09-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha_asistencia', 'hora_ingreso'], 'verbose_name': 'Registro de Asistencia', 'verbose_name_plural': 'Registros de Asistencia'},
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='documento',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_asistencia',
            field=models.DateField(verbose_name='Fecha de Asistencia'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_ingreso',
            field=models.TimeField(verbose_name='Hora de Ingreso'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='nombre_completo',
            field=models.CharField(max_length=150, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Notas u Observaciones'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='presente',
            field=models.BooleanField(default=True, verbose_name='¿Estuvo Presente?'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('documento', 'fecha_asistencia')},
        ),
    ]
