# Generated by Django 5.2.6 on 2025-09-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('academica', 'Académica'), ('administrativa', 'Administrativa'), ('tecnica', 'Técnica'), ('otra', 'Otra')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
